// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/dashboard": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Operations"
                ],
                "summary": "Get operational dashboard totals",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httpapi.DataResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/operations.Dashboard"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpapi.APIError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/httpapi.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpapi.APIError"
                        }
                    }
                }
            }
        },
        "/api/v1/movements": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Records an IN or OUT transaction. Retries must reuse the same Idempotency-Key and request body. IN requires inCategory only. OUT requires BENGKEL_LUAR with workOrderNumber, FILLING_SHED_KUIN or CUSTOMER with sppNumber, or OTHER with driverId, driverName, and note.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Movements"
                ],
                "summary": "Record a unit movement",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID generated once per movement",
                        "name": "Idempotency-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Movement request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httpapi.movementRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httpapi.DataResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/movement.Transaction"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpapi.APIError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpapi.APIError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/httpapi.APIError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httpapi.APIError"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/httpapi.APIError"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/httpapi.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpapi.APIError"
                        }
                    }
                }
            }
        },
        "/api/v1/transactions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Operations"
                ],
                "summary": "List transactions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search no_lambung or no_polisi",
                        "name": "query",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "IN",
                            "OUT"
                        ],
                        "type": "string",
                        "description": "Movement direction",
                        "name": "direction",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "IN category or OUT destination",
                        "name": "detail",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Inclusive RFC3339 UTC timestamp",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Exclusive RFC3339 UTC timestamp",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 25,
                        "description": "Page size",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httpapi.ListResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/operations.Transaction"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpapi.APIError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpapi.APIError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/httpapi.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpapi.APIError"
                        }
                    }
                }
            }
        },
        "/api/v1/transactions/export": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "text/csv"
                ],
                "tags": [
                    "Operations"
                ],
                "summary": "Export transactions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search no_lambung or no_polisi",
                        "name": "query",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "IN",
                            "OUT"
                        ],
                        "type": "string",
                        "description": "Movement direction",
                        "name": "direction",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "IN category or OUT destination",
                        "name": "detail",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Inclusive RFC3339 UTC timestamp",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Exclusive RFC3339 UTC timestamp",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpapi.APIError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpapi.APIError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/httpapi.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpapi.APIError"
                        }
                    }
                }
            }
        },
        "/api/v1/units": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Operations"
                ],
                "summary": "List units",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search no_lambung or no_polisi",
                        "name": "query",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "IN",
                            "OUT",
                            "NULL"
                        ],
                        "type": "string",
                        "description": "Current direction",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "BENGKEL_LUAR",
                            "FILLING_SHED_KUIN",
                            "CUSTOMER",
                            "OTHER"
                        ],
                        "type": "string",
                        "description": "Current OUT destination",
                        "name": "destination",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Include inactive units",
                        "name": "includeInactive",
                        "in": "query"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 25,
                        "description": "Page size",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httpapi.ListResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/operations.Unit"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpapi.APIError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/httpapi.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpapi.APIError"
                        }
                    }
                }
            }
        },
        "/api/v1/units/export": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "text/csv"
                ],
                "tags": [
                    "Operations"
                ],
                "summary": "Export units",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search no_lambung or no_polisi",
                        "name": "query",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "IN",
                            "OUT",
                            "NULL"
                        ],
                        "type": "string",
                        "description": "Current direction",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "BENGKEL_LUAR",
                            "FILLING_SHED_KUIN",
                            "CUSTOMER",
                            "OTHER"
                        ],
                        "type": "string",
                        "description": "Current OUT destination",
                        "name": "destination",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Include inactive units",
                        "name": "includeInactive",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpapi.APIError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/httpapi.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpapi.APIError"
                        }
                    }
                }
            }
        },
        "/api/v1/units/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Operations"
                ],
                "summary": "Get unit detail",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "Unit Lambung ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httpapi.DataResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/operations.Unit"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpapi.APIError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpapi.APIError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/httpapi.APIError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httpapi.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpapi.APIError"
                        }
                    }
                }
            }
        },
        "/api/v1/units/{id}/transactions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Operations"
                ],
                "summary": "List unit transactions",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "Unit Lambung ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 25,
                        "description": "Page size",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httpapi.ListResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/operations.Transaction"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpapi.APIError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpapi.APIError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/httpapi.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpapi.APIError"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "httpapi.APIError": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "object",
                    "properties": {
                        "code": {
                            "type": "string",
                            "example": "VALIDATION_ERROR"
                        },
                        "message": {
                            "type": "string",
                            "example": "movement input is invalid"
                        }
                    }
                }
            }
        },
        "httpapi.DataResponse": {
            "type": "object",
            "properties": {
                "data": {}
            }
        },
        "httpapi.ListResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "pagination": {
                    "$ref": "#/definitions/operations.Page"
                }
            }
        },
        "httpapi.movementRequest": {
            "type": "object",
            "required": [
                "direction",
                "noLambung"
            ],
            "properties": {
                "direction": {
                    "description": "Required for all movements. IN requires inCategory; OUT requires outDestination and its matching fields.",
                    "enum": [
                        "IN",
                        "OUT"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/movement.Direction"
                        }
                    ],
                    "example": "OUT"
                },
                "driverId": {
                    "description": "Required only when outDestination is OTHER.",
                    "type": "integer",
                    "example": 42
                },
                "driverName": {
                    "description": "Required only when outDestination is OTHER.",
                    "type": "string",
                    "example": "Driver Name"
                },
                "inCategory": {
                    "description": "Required only for IN. Must not be supplied for OUT.",
                    "type": "string",
                    "enum": [
                        "WAITING_FOR_ASSIGNMENT",
                        "WAITING_FOR_DELIVERY_TO_CUSTOMER",
                        "SERVICE_AND_REPAIR_MAINTENANCE"
                    ]
                },
                "noLambung": {
                    "description": "Required for all movements.",
                    "type": "string",
                    "example": "SAMT223"
                },
                "note": {
                    "description": "Required only when outDestination is OTHER; optional for other OUT destinations.",
                    "type": "string",
                    "example": "Operational note"
                },
                "outDestination": {
                    "description": "Required only for OUT. Must not be supplied for IN.",
                    "type": "string",
                    "enum": [
                        "BENGKEL_LUAR",
                        "FILLING_SHED_KUIN",
                        "CUSTOMER",
                        "OTHER"
                    ]
                },
                "sppNumber": {
                    "description": "Required only when outDestination is FILLING_SHED_KUIN or CUSTOMER.",
                    "type": "string",
                    "example": "SPP-001"
                },
                "workOrderNumber": {
                    "description": "Required only when outDestination is BENGKEL_LUAR.",
                    "type": "string",
                    "example": "WO-001"
                }
            }
        },
        "movement.Direction": {
            "type": "string",
            "enum": [
                "IN",
                "OUT"
            ],
            "x-enum-varnames": [
                "DirectionIn",
                "DirectionOut"
            ]
        },
        "movement.Transaction": {
            "type": "object",
            "properties": {
                "actorId": {
                    "type": "string"
                },
                "actorName": {
                    "type": "string"
                },
                "customerId": {
                    "type": "string",
                    "x-nullable": "true"
                },
                "customerName": {
                    "type": "string",
                    "x-nullable": "true"
                },
                "direction": {
                    "$ref": "#/definitions/movement.Direction"
                },
                "driverId": {
                    "type": "integer",
                    "x-nullable": "true"
                },
                "driverName": {
                    "type": "string",
                    "x-nullable": "true"
                },
                "inCategory": {
                    "type": "string",
                    "x-nullable": "true"
                },
                "lambungUnitId": {
                    "type": "integer"
                },
                "noLambung": {
                    "type": "string"
                },
                "noPolisi": {
                    "type": "string"
                },
                "note": {
                    "type": "string",
                    "x-nullable": "true"
                },
                "occurredAt": {
                    "type": "string"
                },
                "outDestination": {
                    "type": "string",
                    "x-nullable": "true"
                },
                "sppNumber": {
                    "type": "string",
                    "x-nullable": "true"
                },
                "transactionId": {
                    "type": "integer"
                },
                "workOrderNumber": {
                    "type": "string",
                    "x-nullable": "true"
                }
            }
        },
        "operations.Dashboard": {
            "type": "object",
            "properties": {
                "totalUnits": {
                    "type": "integer"
                },
                "unitsIn": {
                    "type": "integer"
                },
                "unitsNoStatus": {
                    "type": "integer"
                },
                "unitsOut": {
                    "type": "integer"
                }
            }
        },
        "operations.Page": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                },
                "totalItems": {
                    "type": "integer"
                }
            }
        },
        "operations.Transaction": {
            "type": "object",
            "properties": {
                "actorName": {
                    "type": "string"
                },
                "customerName": {
                    "type": "string",
                    "x-nullable": "true"
                },
                "direction": {
                    "type": "string"
                },
                "driverName": {
                    "type": "string",
                    "x-nullable": "true"
                },
                "inCategory": {
                    "type": "string",
                    "x-nullable": "true"
                },
                "noLambung": {
                    "type": "string"
                },
                "noPolisi": {
                    "type": "string"
                },
                "note": {
                    "type": "string",
                    "x-nullable": "true"
                },
                "occurredAt": {
                    "type": "string"
                },
                "outDestination": {
                    "type": "string",
                    "x-nullable": "true"
                },
                "sppNumber": {
                    "type": "string",
                    "x-nullable": "true"
                },
                "transactionId": {
                    "type": "integer"
                },
                "workOrderNumber": {
                    "type": "string",
                    "x-nullable": "true"
                }
            }
        },
        "operations.Unit": {
            "type": "object",
            "properties": {
                "direction": {
                    "type": "string",
                    "x-nullable": "true"
                },
                "driverName": {
                    "type": "string",
                    "x-nullable": "true"
                },
                "durationSeconds": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "inCategory": {
                    "type": "string",
                    "x-nullable": "true"
                },
                "isActive": {
                    "type": "boolean"
                },
                "lastUpdatedAt": {
                    "type": "string",
                    "x-nullable": "true"
                },
                "noLambung": {
                    "type": "string"
                },
                "noPolisi": {
                    "type": "string"
                },
                "outDestination": {
                    "type": "string",
                    "x-nullable": "true"
                },
                "status": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Auth Service JWT using the ` + "`" + `Bearer \u003ctoken\u003e` + "`" + ` format.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "UnitLog Pool Basirih API",
	Description:      "API for immutable truck IN/OUT movements and pool operations.\nMovement scans require `unitlog:app:default:view`, actor ID/name claims, and an Idempotency-Key UUID. Operations require `unitlog:web:default:view`.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
